<?xml version="1.0" encoding="UTF-8"?>
<testrun name="UndoManagerTest" project="UndoManager" tests="9" started="9" failures="1" errors="0" ignored="0">
  <testsuite name="undo.UndoManagerTest" time="0.023">
    <testcase name="testBufferCreation" classname="undo.UndoManagerTest" time="0.008"/>
    <testcase name="testBufferAdd" classname="undo.UndoManagerTest" time="0.001"/>
    <testcase name="testInsertion" classname="undo.UndoManagerTest" time="0.002"/>
    <testcase name="testInsertionUndoRedo" classname="undo.UndoManagerTest" time="0.007">
      <failure>
        <expected>Hello,worldHello</expected>
        <actual>Hello,world</actual>junit.framework.ComparisonFailure: null expected:&lt;Hello,world[Hello]&gt; but was:&lt;Hello,world[]&gt;
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at undo.UndoManagerTest.testInsertionUndoRedo(UndoManagerTest.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</failure>
    </testcase>
    <testcase name="testUndoSingleItem" classname="undo.UndoManagerTest" time="0.001"/>
    <testcase name="testUndoMultipleItems" classname="undo.UndoManagerTest" time="0.0"/>
    <testcase name="testRedoSingleItem" classname="undo.UndoManagerTest" time="0.001"/>
    <testcase name="testUndoRedoMultipleTimes" classname="undo.UndoManagerTest" time="0.001"/>
    <testcase name="testAddAfterUndoRedo" classname="undo.UndoManagerTest" time="0.001"/>
  </testsuite>
</testrun>
